# Generated by Django 5.1.5 on 2025-02-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('address_line_1', models.CharField(default='No address', max_length=128)),
                ('address_line_2', models.CharField(blank=True, max_length=128, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=125)),
                ('state', models.CharField(max_length=125)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'other')], max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
