# Generated by Django 5.1.5 on 2025-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MEDICINE', 'Medicine'), ('HEALTHCARE', 'Healthcare'), ('WELLNESS', 'Wellness'), ('PERSONAL_CARE', 'Personal Care')], max_length=64),
        ),
    ]
