# Generated by Django 5.1.5 on 2025-02-16 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PRESCRIPTION_MEDICINES', 'Prescription Medicines'), ('HEALTHCARE_DEVICES', 'Healthcare Devices'), ('SURGICAL_PRODUCTS', 'Surgical Products'), ('AYURVEDIC_MEDICINES', 'Ayurvedic Medicines'), ('PERSONAL_CARE', 'Personal Care'), ('BEAUTY_PRODUCTS', 'Beauty Products'), ('GROCERY_PRODUCTS', 'Grocery Products'), ('FITNESS_ENTHUSIASTS', 'Fitness Enthusiasts'), ('BABY_PRODUCTS', 'Baby Products'), ('SEX_AWARE_PRODUCTS', 'Sex Aware Products'), ('HOUSEHOLD_PRODUCTS', 'Household Products'), ('PET_PRODUCTS', 'Pet Products')], max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/create/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
    ]
